# Generated by Django 2.2.2 on 2019-06-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=100, unique=True)),
                ('question', models.ForeignKey(on_delete='SET_NULL', to='exam.Question')),
            ],
        ),
    ]
