# Generated by Django 2.2.2 on 2019-06-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20190607_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', related_name='choice', to='exam.Choice'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', related_name='question', to='exam.Question'),
        ),
    ]
