# Generated by Django 2.2.2 on 2019-06-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20190607_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='exam.Tag'),
        ),
    ]
